version: "3.8"

services:
  nctl-container:
    build:
      context: ./nctl-container
      dockerfile: Dockerfile
    environment:
      PREDEFINED_ACCOUNTS: "true"
      DEPLOY_DELAY: "5sec"
    networks:
      - fondant-network

  lean-api:
    build:
      context: ./lean-api
      dockerfile: Dockerfile
    ports:
      - "3001:3000" 
    networks:
      - fondant-network

  react-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - fondant-network

networks:
  fondant-network:
    driver: bridge

volumes:
  app-volume:
