version: "2.1"

services:
  fondant-nctl-container:
    build:
      context: ./nctl-container
      dockerfile: Dockerfile
    environment:
      PREDEFINED_ACCOUNTS: "true"
      DEPLOY_DELAY: "5sec"
    networks:
      - fondant-network

  fondant-lean-api:
    build:
      context: ./lean-api
      dockerfile: Dockerfile
    ports:
      - "3001:3000" 
    networks:
      - fondant-network

  fondant-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - fondant-network

networks:
  fondant-network:
    driver: bridge

volumes:
  app-volume:
