openapi: 3.0.3
info:
  version: 1.0.1
  title: NCTL-API
  description: NCTL-API is a RESTful API for interacting with NCTL network.

servers:
  - url: http://localhost:3000

paths:
  /health-check:
    get:
      summary: Check API Health
      responses:
        '200':
          description: API is running
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /nctl-start:
    post:
      summary: Start NCTL process
      responses:
        '200':
          description: NCTL process started successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  parsedResponse:
                    type: object
        '500':
          description: Internal Server Error

  /nctl-status:
    post:
      summary: Get NCTL status
      responses:
        '200':
          description: NCTL running status
          content:
            text/plain:
              schema:
                type: string
        '503':
          description: Service Unavailable
        '500':
          description: Internal Server Error

  /faucet:
    get:
      summary: View NCTL faucet account
      responses:
        '200':
          description: Faucet account details
          content:
            text/plain:
              schema:
                type: string
        '500':
          description: Internal Server Error

  /faucet-private-key:
    get:
      summary: Get faucet secret key
      responses:
        '200':
          description: Returns content of faucet secret key file
          content:
            text/plain:
              schema:
                type: string
        '500':
          description: Internal Server Error

  /nctl-view-user-account/{userNumber}:
    get:
      summary: View user accounts
      parameters:
        - in: path
          name: userNumber
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User account details
          content:
            text/plain:
              schema:
                type: string
        '500':
          description: Internal Server Error

  /user-keys/{userNumber}:
    get:
      summary: Get user private and public keys
      parameters:
        - in: path
          name: userNumber
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Private and public keys of the user
          content:
            application/json:
              schema:
                type: object
                properties:
                  private_key:
                    type: string
                  public_key:
                    type: string
        '500':
          description: Internal Server Error

  /cache/events/{nodeNumber}:
    get:
      summary: Fetch cached events for a specific node
      parameters:
        - in: path
          name: nodeNumber
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Cached events for the node
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Invalid node number
        '404':
          description: No events found
        '500':
          description: Internal Server Error

  /cache/deploys/{nodeNumber}:
    get:
      summary: Fetch deploy events for a specific node
      parameters:
        - in: path
          name: nodeNumber
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Deploy events for the node
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Invalid node number
        '404':
          description: No deploy events found
        '500':
          description: Internal Server Error

  /logs/{nodeNumber}:
    get:
      summary: Fetch logs for a specific node
      parameters:
        - in: path
          name: nodeNumber
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Logs of the node
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
        '500':
          description: Internal Server Error

  /transfer:
    post:
      summary: Perform a transfer
      responses:
        '200':
          description: Transfer completed
          content:
            text/plain:
              schema:
                type: string
        '500':
          description: Internal Server Error

  /get-default-chainspec:
    get:
      summary: Get default chainspec
      responses:
        '200':
          description: Default chainspec data
          content:
            text/plain:
              schema:
                type: string
        '500':
          description: Internal Server Error

  /set-chainspec:
    post:
      summary: Set chainspec data
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Chainspec set successfully
          content:
            application/json:
              schema:
                type: object
        '500':
          description: Internal Server Error
