version: "3.8"

services:
  fondant-nctl-container:
    image: blockbites/fondant-nctl-container
    environment:
      PREDEFINED_ACCOUNTS: "true"
      DEPLOY_DELAY: "5sec"
    networks:
      - fondant-network

  fondant-lean-api:
    image: blockbites/fondant-lean-api
    ports:
      - "3001:3000" 
    networks:
      - fondant-network

  fondant-frontend:
    image: blockbites/fondant-frontend
    ports:
      - "3000:3000"
    networks:
      - fondant-network

networks:
  fondant-network:
    driver: bridge

volumes:
  app-volume:

